---
- name: qbittorrent | Ensure that the Qbittorrent config directory exists
  ansible.builtin.file:
    path: "{{ services_arr_volume_storage }}/qbittorrent/_data/qBittorrent"
    owner: "qbittorrent"
    group: "qbittorrent"
    mode: '0755'
    state: directory
  become: true

- name: qbittorrent | Create Qbittorrent Configuration
  ansible.builtin.template:
    src: "{{ services_arr_config_file }}"
    dest: "{{ services_arr_volume_storage }}/qbittorrent/_data/qBittorrent/{{ services_arr_config_file | basename | regex_replace('\\.j2$') }}"
    owner: "qbittorrent"
    group: "qbittorrent"
    mode: '0644'
  with_fileglob: "{{ role_path }}/templates/qBittorrent/*.j2"
  loop_control:
    loop_var: services_arr_config_file
  register: qbittorrent_configs
  become: true
