services_gitea_container_version: "latest"
services_gitea_mariadb_version: "latest"
services_gitea_volumes:
  - /opt/gitea:/data
  - /etc/timezone:/etc/timezone:ro
  - /etc/localtime:/etc/localtime:ro
services_gitea_mariadb_volumes:
  - /var/gitea/db:/data
