services_gitea_container_version: "latest"
services_gitea_mariadb_version: "latest"
services_gitea_volumes:
  gitea:
    /opt/gitea: /data
    /home/git/.ssh: /data/git/.ssh
    /etc/timezone: /etc/timezone:ro
    /etc/localtime: /etc/localtime:ro
  gitea_db:
    /var/gitea/db: /var/lib/mysql
    /etc/timezone: /etc/timezone:ro
    /etc/localtime: /etc/localtime:ro
services_gitea_podman_uid_mappings:
  git: {start: 20000, count: 65536}

services_gitea_backup_kit:
  name: gitea-data
  server: "sftp:backupsys@10.3.1.3"
  # Options: minutely, hourly, daily, weekly, monthly
  freq: daily
