[tools]
python = "3.13"
node = "latest"
"npm:ansible-language-server" = "latest"

[env]
ANSIBLE_FORCE_COLOR = "True"
_.python.venv = {path = ".venv", create = true }

[tasks.playbook]
run = ['./run.sh ansible-playbook -K ']

[tasks.deploy-keys]
run = ['./run.sh ansible-playbook -k playbooks/deploy_ssh_keys.yml ']

[tasks.lint]
run = """
.githooks/pre-commit
"""
