---
- name: dependencies | Fedora-41 | Enable Hashicorp RPM Repository
  ansible.builtin.copy:
    src: Fedora-41/hashicorp.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: '0644'
  become: true

- name: dependencies | Fedora-41 | Install Terraform and Packer
  ansible.builtin.dnf:
    name: ['terraform', 'packer', python3-libdnf5]
    state: present
  become: true
