all:

  children:
    proxmox:
      hosts:
        intel-nuc-13-01.sti.com:
          # Note the typo of 'inte' is reflective of the name on proxmox.
          proxmox_node_id: inte-nuc-13-01
          api_uri: https://intel-nuc-13-01.sti.com:8006/api2/json
          templates:
            - name: debian-12-base
              id: 8000
              desc: "Debian 12 Bookwork template"
        intel-nuc-13-02.sti.com:
          proxmox_node_id: intel-nuc-13-02
          api_uri: https://intel-nuc-13-02.sti.com:8006/api2/json
        intel-nuc-13-03.sti.com:
          proxmox_node_id: intel-nuc-13-03
          api_uri: https://intel-nuc-13-03.sti.com:8006/api2/json

    virtual_machines:
      hosts:
        gitea.local.silicontech.us:
          ansible_host: 10.2.41.5
          target_host: intel-nuc-13-01.sti.com
          from_template: debian-12-base
          guest_info:
            id: 501
            desc: The virtualized Gitea host
            tags: debian_12,service,infrastructure_as_code
            start_on_boot: true
            gateway: 10.2.40.1
            pool: infrastructure
            cidr: /24
            disk:
              size: 64G
            compute:
              sockets: 4
              memory: 8192


    # kubernetes:
    #   hosts:
    #     k3s-01.local.silicontech.us:
    #       ansible_host: 10.2.41.2
    #       target_host: inte-nuc-13-01.sti.com
    #       guest_info:
    #         id: 401
    #         cidr: /24
    #         gateway: 10.2.40.1
    #     k3s-02.local.silicontech.us:
    #       ansible_host: 10.2.41.3
    #       target_host: intel-nuc-13-02.sti.com
    #       guest_info:
    #         id: 401
    #         cidr: /24
    #         gateway: 10.2.40.1
    #     k3s-03.local.silicontech.us:
    #       ansible_host: 10.2.41.4
    #       target_host: intel-nuc-13-03.sti.com
    #       guest_info:
    #         id: 401
    #         cidr: /24
    #         gateway: 10.2.40.1
