all:

  children:
    proxmox:
      hosts:
        pve.local.wolfbox.dev:
          # Note the typo of 'inte' is reflective of the name on proxmox.
          proxmox_node_id: pve
          api_uri: https://pve.local.wolfbox.dev:8006/api2/json
          templates:
            - name: debian-12-base
              id: 8000
              desc: "Debian 12 Bookwork template"

    virtual_machines:
      hosts:
        ldap.local.wolfbox.dev:
          ansible_host: 192.168.41.7
          ansible_user: cluster
          target_host: pve.local.wolfbox.dev
          guest_info:
            id: 501
            desc: The OpenLDAP Host
            tags: debian_12,service,infrastructure_as_code
            gateway: 192.168.40.21
            cidr: /21

        arr.local.wolfbox.dev:
          ansible_host: 192.168.41.8
          ansible_user: cluster
          target_host: pve.local.wolfbox.dev
          guest_info:
            id: 502
            desc: The Arr service host
            tags: debian_12,service,infrastructure_as_code
            gateway: 192.168.40.21
            cidr: /21
            compute:
              cores: 2
              memory: 12288
            disk:
              size: 35G
            firewall:
              options:
                enable: 1
                policy_out: DROP
                log_level_out: info
                log_level_in: info
              rules:
                - "OUT LDAPS(ACCEPT) \
                  -dest +dc/home-lab \
                  -log nolog # OpenLDAP server"
                - "OUT ACCEPT \
                  -dest +dc/pia-vpn \
                  -log nolog \
                  # Allow connections to the Pirvate Internet Access Servers"
                - "IN SSH(ACCEPT) -source +dc/home-lab -log nolog"
                - "IN ACCEPT -source +dc/home-lab -p tcp -dport 8080 -log nolog # Qbittorrent"
                - "IN ACCEPT -source +dc/home-lab -p tcp -dport 6881 -log nolog # Qbittorrent"
                - "IN ACCEPT -source +dc/home-lab -p udp -dport 6881 -log nolog # Qbittorrent"
                - "IN ACCEPT -source +dc/home-lab -p tcp -dport 9696 -log nolog # Prowlarr"
                - "IN ACCEPT -source +dc/home-lab -p tcp -dport 7878 -log nolog # Radarr"
                - "IN ACCEPT -source +dc/home-lab -p tcp -dport 8989 -log nolog # Sonarr"
                - "IN ACCEPT -source +dc/home-lab -p tcp -dport 8787 -log nolog # Readarr"
                - "IN ACCEPT -source +dc/home-lab -p tcp -dport 5055 -log nolog # Overseerr"
                - "OUT ACCEPT -dest +dc/home-lab -p tcp -dport 32400 -log nolog # Overseerr to Plex"
                - "OUT DNS(DROP) -log nolog # Disable logging invalid DNS queires"
                - "OUT ACCEPT -p tcp -dport 1337 -log nolog \
                  # Private Internet Access - Wireguard Connection"
                - "OUT ACCEPT -p udp -dport 1337 -log nolog \
                  # Private Internet Access - Wireguard Connection"
                - "OUT ACCEPT -dest +dc/home-lab -p tcp -dport 2049 -log nolog
                  # Allow NFS mounts"

        gitea.local.wolfbox.dev:
          ansible_host: 192.168.41.9
          target_host: pve.local.wolfbox.dev
          from_template: debian-12-base
          guest_info:
            id: 503
            desc: The virtualized Gitea host
            tags: debian_12,service,infrastructure_as_code
            gateway: 192.168.40.21
            cidr: /21
          firewall:
            options:
              enable: 1
              log_level_in: info
            rules:
              - "IN SSH(ACCEPT) -source +dc/home-lab -log nolog"
              - "IN HTTPS(ACCEPT) -source +dc/home-lab -log nolog"

