all:

  children:
    proxmox:
      hosts:
        intel-nuc-13-01.sti.com:
          # Note the typo of 'inte' is reflective of the name on proxmox.
          proxmox_node_id: inte-nuc-13-01
          api_uri: https://intel-nuc-13-01.sti.com:8006/api2/json
        intel-nuc-13-02.sti.com:
          proxmox_node_id: intel-nuc-13-02
          api_uri: https://intel-nuc-13-02.sti.com:8006/api2/json
        intel-nuc-13-03.sti.com:
          proxmox_node_id: intel-nuc-13-03
          api_uri: https://intel-nuc-13-03.sti.com:8006/api2/json

    kubernetes:
      hosts:
        k3s-01.local.wolfbox.dev:
          target_host: intel-nuc-13-01.sti.com
          guest_info:
            id: 401
            ipv4: 10.2.41.2/24
            gateway: 10.2.40.1
        k3s-02.local.wolfbox.dev:
          target_host: intel-nuc-13-02.sti.com
          guest_info:
            id: 401
            ipv4: 10.2.41.3/24
            gateway: 10.2.40.1
        k3s-03.local.wolfbox.dev:
          target_host: intel-nuc-13-03.sti.com
          guest_info:
            id: 401
            ipv4: 10.2.41.4/24
            gateway: 10.2.40.1
