all:

  children:
    proxmox:
      hosts:
        pve.local.wolfbox.dev:
          # Note the typo of 'inte' is reflective of the name on proxmox.
          proxmox_node_id: pve
          api_uri: https://pve.local.wolfbox.dev:8006/api2/json
          templates:
            - name: debian-12-base
              id: 8000
              desc: "Debian 12 Bookwork template"

    virtual_machines:
      hosts:
        ldap.local.wolfbox.dev:
          ansible_host: 192.168.41.7
          ansible_user: cluster
          target_host: pve.local.wolfbox.dev
          guest_info:
            id: 501
            desc: The OpenLDAP Host
            tags: debian_12,service,infrastructure_as_code
            gateway: 192.168.40.21
