all:

  children:
    proxmox:
      hosts:
        pve.local.wolfbox.dev:
          proxmox_node_id: pve.local.wolfbox.dev
          api_uri: https://pve.local.wolfbox.dev:8006/api2/json

    kubernetes:
      hosts:
        k3s-01.local.wolfbox.dev:
          target_host: pve
          guest_info:
            id: 401
            ipv4: 192.168.20.2/24
            gateway: 192.168.86.1
        k3s-02.local.wolfbox.dev:
          target_host: pve
          guest_info:
            id: 402
            ipv4: 192.168.20.3/24
            gateway: 192.168.86.1
        k3s-03.local.wolfbox.dev:
          target_host: pve
          guest_info:
            id: 403
            ipv4: 192.168.20.4/24
            gateway: 192.168.86.1
