---
- name: Debian-12 | Enable 1Password APT repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 \
      signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] \
      https://downloads.1password.com/linux/debian/amd64 \
      stable main"
    state: present
  become: true

- name: Debian-12 | Install 1Password CLI
  ansible.builtin.apt:
    name: 1password-cli
    state: present
  become: true
