services_openldap_container_name: openldap

services_openldap_container_ports:
  # - "389:389" # ldap://
  - "636:636" # ldaps

services_openldap_podman_build_images:
  - name: "{{ services_openldap_container_name }}"
    container_file_content: "{{ lookup('file', 'openldap.containerfile') }}"

services_openldap_main_storage: "/var/lib/containers/storage/volumes/{{ services_openldap_container_name }}/_data"

services_openldap_container_spec:
  - name: "{{ services_openldap_container_name }}"
    image_url: "localhost/{{ services_openldap_container_name }}"
    volumes:
      - src: /etc/openldap/ldap.conf
        target: /etc/openldap/ldap.conf
      - src: /etc/openldap/slapd.conf
        target: /etc/openldap/slapd.conf
      - src: /etc/openldap/slapd.ldif
        target: /etc/openldap/slapd.ldif
      - name: "{{ services_openldap_container_name }}_db"
        target: /var/lib/openldap/openldap-data
      - name: certbot
        target: /srv/certbot:ro
