podman_pod_build_images: "{{ lookup('community.general.merge_variables', '_podman_build_images', pattern_type='suffix') }}"

podman_pod_spec:
  name: "{{ podman_pod_name | default('deployed_pod') }}"
  ports: "{{ lookup('community.general.merge_variables', '_container_ports', pattern_type='suffix') }}"
  containers: "{{ lookup('community.general.merge_variables', '_container_spec', pattern_type='suffix') }}"

podman_pod_named_volumes: "{{ podman_pod_spec.containers \
  | map(attribute='volumes') \
  | flatten \
  | selectattr('name', 'defined') }}"

podman_pod_storage: "/var/lib/containers/storage/volumes"
