- name: post-processing | Fedora-40 | Configure authselect to use sssd authentication
  block:
    - name: post-processing | Fedora-40 | Check if authselect profile is already set to sssd
      ansible.builtin.command: authselect current
      register: authselect_status
      changed_when: false
      failed_when: authselect_status.rc not in [0, 2]
      become: true

    - name: post-processing | Fedora-40 | Apply authselect profile with sssd and compatible features if not already configured
      ansible.builtin.command: authselect select -bf {{ ldap_client_authselect_profiles | join(' ') }}
      when: "'Profile ID: sssd' not in authselect_status.stdout"
      become: true
