---
- name: container | "Create the container user's group | {{ podman_pod_container.name }}"
  ansible.builtin.user:
    name: "{{ podman_pod_container.name }}"
    system: true
    state: present
  become: true

- name: container | "Create the container user | {{ podman_pod_container.name }}"
  ansible.builtin.user:
    name: "{{ podman_pod_container.name }}"
    group: "{{ podman_pod_container.name }}"
    system: true
    state: present
    password_lock: true
    password: '!' # Sets the password as a locked password
    generate_ssh_key: true
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: ed25519
  register: container_user
  become: true

- name: container | "Ensure the container host can ssh into the container | {{ podman_pod_container.name }}"
  ansible.posix.authorized_key:
    user: "{{ container_user.name }}"
    state: present
    key: "{{ container_user.ssh_public_key }}"
  become: true

- name: container | "Create the container's systemd service file | {{ podman_pod_container.name }}"
  ansible.builtin.template:
    src: podman.service.j2
    dest: /etc/systemd/system/{{ podman_pod_container.name }}_podman.service
    owner: root
    group: root
    mode: '0600'
  register: podman_pod_container_systemd_unit_file
  become: true

- name: container | Reload the Systemd Daemons
  ansible.builtin.systemd_service:
    name: "{{ podman_pod_container.name }}_podman.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
  when: podman_pod_container_systemd_unit_file.changed or (container_image is defined and container_image.changed)
