services_snipeit_container_name: snipeit
services_snipeit_database_name: "{{ services_snipeit_container_name }}"

services_snipeit_container_ports:
  - "443:443"
  - "127.0.0.1:3306:3306"

services_snipeit_main_storage: "{{ podman_pod_storage }}/{{ services_snipeit_container_name }}/_data"

services_snipeit_container_spec:
  - name: "{{ services_snipeit_container_name }}_db"
    image_url: docker.io/library/mariadb
    image_version: "latest"
    volumes:
      - name: "{{ services_snipeit_container_name }}_db"
        target: /var/lib/mysql
      - src: /etc/timezone
        target: /etc/timezone:ro
      - src: /etc/localtime
        target: /etc/localtime:ro
    envs:
      MARIADB_ROOT_PASSWORD: "{{ lookup('env', 'SNIPEIT_DB_PASSWORD') }}"

  - name: "{{ services_snipeit_container_name }}"
    image_url: docker.io/snipe/snipe-it
    image_version: "latest"
    volumes:
      - name: "{{ services_snipeit_container_name }}"
        target: /var/lib/snipeit
      - src: /etc/timezone
        target: /etc/timezone:ro
      - src: /etc/localtime
        target: /etc/localtime:ro
    env_files:
      - "{{ services_snipeit_main_storage }}/snipeit.env"
    systemd:
      requires:
        - "{{ services_snipeit_container_name }}_db_podman.service"
      after:
        - "{{ services_snipeit_container_name }}_db_podman.service"
