ldap_client_expiration_days: 4
ldap_client_server: ldaps://ldap.local.wolfbox.dev
ldap_client_base_dn: dc=wolfbox,dc=dev
ldap_client_access_condition: (&(objectClass=posixAccount)(uidNumber>=1000))
ldap_client_authselect_profiles:
  - sssd
  - with-sudo
  - with-silent-lastlog
  - with-mdns4
  - with-fingerprint
  - with-mkhomedir
