- name: Ensure dependencies are installed
  ansible.builtin.package:
    name:
      - podman
      - fuse-overlayfs
    state: present
  become: true

- name: Create the Gitea pod
  containers.podman.podman_pod:
    name: gitea-pod
    state: started
    ports:
      - "443:3000"
      - "2222:2222"
      - "127.0.0.1:3306:3306"
  become: true

- name: Create directories for Gitea Database
  ansible.builtin.file:
    path: "/var/gitea/db"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create Gitea Database systemd service file
  ansible.builtin.template:
    src: gitea-db-podman.service.j2
    dest: /etc/systemd/system/gitea-db-podman.service
    owner: root
    group: root
    mode: '0600'
  register: gitea_db_systemd_unit
  become: true

- name: Restart the gitea-db-podman.service if there has been a config change
  ansible.builtin.systemd:
    name: gitea-db-podman.service
    enabled: true
    state: restarted
    daemon_reload: true
  when: gitea_db_systemd_unit.changed
  become: true

- name: Pause for 10 seconds for container to come up
  ansible.builtin.pause:
    seconds: 10
  when: gitea_db_systemd_unit.changed

- name: Initialize the Gitea DB Scheme
  block:
    - name: Install database modification requirements
      ansible.builtin.package:
        name:
          - mariadb-server
          - python3-pymysql
        state: present
      become: true

    - name: Define the database within the mariadb server
      community.mysql.mysql_db:
        name: gitea
        state: present
        login_host: 127.0.0.1
        login_user: "{{ lookup('env', 'GITEA_DB_USERNAME') }}"
        login_password: "{{ lookup('env', 'GITEA_DB_PASSWORD') }}"

- name: Create directories for Gitea
  ansible.builtin.file:
    path: "/opt/gitea/gitea/conf"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create Gitea Podman systemd service file
  ansible.builtin.template:
    src: gitea-podman.service.j2
    dest: /etc/systemd/system/gitea-podman.service
    owner: root
    group: root
    mode: '0600'
  register: gitea_systemd_unit
  become: true

- name: Restart the gitea-podman.service if there has been a config change
  ansible.builtin.systemd:
    name: gitea-podman.service
    enabled: true
    state: restarted
    daemon_reload: true
  when: gitea_systemd_unit.changed
  become: true

- name: Pause for 15 seconds for container to come up
  ansible.builtin.pause:
    seconds: 15
  when: gitea_systemd_unit.changed

- name: Check for Gitea's Certs and generate if needed
  block:
    - name: Check if the certificate exists.changed
      ansible.builtin.stat:
        path: /opt/gitea/gitea/cert.pem
      register: cert_check

    - name: Generate Gitea HTTPS Certificates
      containers.podman.podman_container_exec:
        name: gitea
        command: "gitea cert --host {{ ansible_host }}"
        workdir: /data/gitea
        user: git
      become: true
      when: not cert_check.stat.exists
      notify: Restart Gitea service

- name: Create Gitea Configuration
  block:
    # Because we'll add secrets to our ini file later, We'll only want to
    # compare our template against a configuration without later modifications.
    # We'll call this pre-modified ini the preinstall ini
    - name: Create Gitea Preinstall Configuration
      ansible.builtin.template:
        src: app.ini.j2
        dest: /opt/gitea/gitea/conf/app.preinstall.ini
        owner: 1000
        group: 1000
        mode: '0600'
      register: gitea_preinstall_conf
      become: true

    - name: Create Gitea Configuration
      ansible.builtin.copy:
        remote_src: true
        src: /opt/gitea/gitea/conf/app.preinstall.ini
        dest: /opt/gitea/gitea/conf/app.ini
        owner: 1000
        group: 1000
        mode: '0600'
      notify: Restart Gitea service
      when: gitea_preinstall_conf.changed
      become: true

    - name: Generate Gitea Secrets
      containers.podman.podman_container_exec:
        name: gitea
        command: >
          bash -c
          'gitea generate secret INTERNAL_TOKEN &&
          gitea generate secret JWT_SECRET &&
          gitea generate secret SECRET_KEY'
        user: git
      become: true
      when: gitea_preinstall_conf.changed
      notify: Restart Gitea service

- name: Ensure the gitea services are up and enabled
  ansible.builtin.systemd:
    name: "{{ services_gitea_unit }}"
    enabled: true
    state: started
  become: true
  loop:
    - gitea-db-podman.service
    - gitea-podman.service
  loop_control:
    loop_var: services_gitea_unit
