---
# If you want to change the port on a SELinux system, you have to tell
# SELinux about this change.
# semanage port -a -t ssh_port_t -p tcp #PORTNUMBER
proxmox_node_host_sshd_port: 22

# Change the methods of authentication.
proxmox_node_host_sshd_password_authentication: "yes"
proxmox_node_host_sshd_pubkey_authentication: "yes"
proxmox_node_host_sshd_challenge_response_authentication: "no"

# Will whitelist users allowed to ssh into a host.
# If empty, all users are allowed.
proxmox_node_host_sshd_allowed_users: []

# Reduce the attach surface of SSH.
proxmox_node_host_sshd_x11_forwarding: "no"
proxmox_node_host_sshd_agent_forwarding: "no"
proxmox_node_host_sshd_tcp_forwarding: "no"

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
# WARNING: 'UsePAM no' is not supported in RHEL and may cause several
# problems.
proxmox_node_host_sshd_use_pam: "yes"
