---
- name: Deploy SSH keys to all hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Add local public key to remote authorized keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
