---
###############################################################################
# Just check to make sure that our become password is correct so we don't
# Attempt to run lots of tasks with an incorrect become password. This
# would lock us out of each machine due to failed password attempts.
###############################################################################
- name: Pre-Checks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if Become's (sudo) password is correct
      ansible.builtin.command: echo "Success"
      become: true
      changed_when: false
      # Only run on one machine, then move on to other the plays
      run_once: true # noqa: run-once[task]
      tags: [always]

###############################################################################
# Configure the current machine running ansible so that it can execute the rest
# of the plays, roles and tasks. This is mostly about installing dependencies,
# ensuring proper firewall rules, etc.
###############################################################################
- name: Setup local control node
  hosts: localhost
  gather_facts: true
  roles:
    - common
    - control_node
    - ldap_client
  tags: ['setup', 'packer', 'local', 'terraform', 'control_node']
  connection: local

###############################################################################
# Configure the proxmox node hosts. This sets up ssh configurations and other
# setup and hardening configurations. This does not deploy any VMs, containers,
# or templates
###############################################################################
- name: Configure the proxmox node hosts
  hosts: proxmox
  gather_facts: false
  roles:
    - proxmox_node_host
  tags: ['setup', 'control_node']

###############################################################################
# Ensure that the proxmox clusters have been setup with the appropriate virtual
# machine templates. These templates will be used to deploy the infrastructure
# with minimal adjustments and setup.
###############################################################################
- name: Templates on Proxmox Servers
  hosts: proxmox
  become: false
  gather_facts: false
  roles:
    - proxmox_vm_template
  tags: ['setup', 'packer', 'templates']

###############################################################################
# Deploy the virtual machines as defined in the inventory
###############################################################################
- name: Deploy Virtual Machines
  hosts: virtual_machines
  become: false
  gather_facts: false
  roles:
    - deploy_vms
  tags: ['setup', 'vms', 'terraform']

###############################################################################
# Deploy the virtual machine configurations
###############################################################################
- name: Deploy Virtual Machine's Configurations
  hosts: virtual_machines
  become: false
  roles:
    - role: ssh
      tags: ['ssh', 'authentication']

    - role: ldap_client
      tags: ['client', 'ldap', 'openldap', 'authentication', 'identity']

    - role: alloy
      become: true
      tags: ['logs', 'monitoring', 'alloy']
  tags: ['setup', 'terraform', 'vms']

###############################################################################
# Deploy the OpenLDAP service
###############################################################################
- name: Deploy the OpenLDAP service
  hosts: ldap.local.wolfbox.dev
  roles:
    - services_openldap
  tags: ['services', 'openldap', 'ldap']

###############################################################################
# Deploy the monitoring services
###############################################################################
- name: Deploy the monitoring service
  hosts: monitoring.local.wolfbox.dev
  roles:
    - services_monitoring
  tags: ['services', 'monitoring']

###############################################################################
# Deploy the arr services
###############################################################################
- name: Deploy the Arr service
  hosts: arr.local.wolfbox.dev
  roles:
    - private_internet_access
    - services_arr
  tags: ['services', 'arr', 'pia']

###############################################################################
# Deploy the gitea services
###############################################################################
- name: Deploy the Gitea service
  hosts: gitea.local.wolfbox.dev
  roles:
    - services_gitea
  tags: ['services', 'gitea']

###############################################################################
# Deploy the n8n services
###############################################################################
- name: Deploy the n8n service
  hosts: n8n.local.wolfbox.dev
  roles:
    - services_n8n
  tags: ['services', 'ai']


###############################################################################
# Deploy the n8n services
###############################################################################
- name: Deploy the openwebui service
  hosts: openwebui.local.wolfbox.dev
  roles:
    - services_openwebui
  tags: ['services', 'ai']

