---
- name: Setup Packer Control Node
  hosts: localhost
  gather_facts: true
  roles:
    - packer_control_node
  tags: ['setup', 'packer']
  connection: local

- name: Templates on Proxmox Servers
  hosts: proxmox
  become: false
  gather_facts: false
  vars:
    templates:
      - name: debian-12-base
        id: 8000
  roles:
    - proxmox_vm_template
  tags: ['setup', 'packer', 'templates']
