---
dependencies:
  - role: podman_pod
    vars:
      podman_pod_name: "{{ services_openldap_container_name }}_pod"
  - role: self_signed_ssl
    vars:
      self_signed_ssl_certificate_owner: "{{ services_openldap_container_name }}"
      self_signed_ssl_certificate_group: "{{ services_openldap_container_name }}"
      self_signed_ssl_certificate_dir: "{{ services_openldap_main_storage }}/certs"
      self_signed_ssl_key_file: ldap_server.key
      self_signed_ssl_certificate_file: ldap_server.crt
